**Install Required Libraries**

In [3]:
pip install fake-useragent

Requirement already satisfied: fake-useragent in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.2.0)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


**Import Required Libraries**

In [4]:
# ============================================================
# CELL 2: IMPORT LIBRARIES
# ============================================================

import requests
import pandas as pd
import re
import time
import hashlib

from bs4 import BeautifulSoup
from tqdm import tqdm
from fake_useragent import UserAgent

from urllib.parse import urljoin

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

**Define Governance URLs**

In [5]:
SEED_URLS = [

    "https://www.eacc.go.ke/",
    "https://www.iebc.or.ke/",
    "https://www.publicservice.go.ke/",
    "https://www.ecitizen.go.ke/",
    "https://immigration.go.ke/",
    "https://ntsa.go.ke/",
    "https://www.health.go.ke/",
    "https://www.parliament.go.ke/",
    "https://mygov.go.ke/",
    "https://www.kra.go.ke/",
    "https://www.odpp.go.ke/",
    "https://www.knchr.org/"

]

**Create a Web Request Function**

In [6]:
# ============================================================
# CELL 4 (Improved)
# ============================================================

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

ua = UserAgent()

HEADERS = {
    "User-Agent": ua.random
}

def fetch_page(url, timeout=30):

    try:

        response = requests.get(
            url,
            headers=HEADERS,
            timeout=timeout,
            verify=False      # Ignore bad SSL certificates
        )

        response.raise_for_status()

        soup = BeautifulSoup(response.text, "lxml")

        time.sleep(1)

        return soup

    except Exception as e:

        print(f"\nFailed: {url}")
        print(e)

        return None

**DISCOVER ALL LINKS**

In [7]:
# ============================================================
# CELL 5: DISCOVER ALL LINKS
# ============================================================

all_links = []

for website in tqdm(SEED_URLS):

    soup = fetch_page(website)

    if soup is None:
        continue

    for link in soup.find_all("a", href=True):

        href = link["href"]

        # Convert relative URLs into absolute URLs
        full_url = urljoin(website, href)

        all_links.append(full_url)

print(f"Total links discovered: {len(all_links)}")

  0%|          | 0/12 [00:00<?, ?it/s]

100%|██████████| 12/12 [00:57<00:00,  4.78s/it]

Total links discovered: 1536

**FILTER GOVERNANCE LINKS**

In [8]:
# ============================================================
# CELL 6: FILTER GOVERNANCE LINKS
# ============================================================

ARTICLE_KEYWORDS = [

    "news",
    "media",
    "press",
    "press-release",
    "announcement",
    "announcements",
    "notice",
    "notices",
    "alert",
    "alerts",
    "update",
    "updates",
    "article",
    "communication",
    "public",
    "events",
    "latest",
    "speech",
    "citizen",
    "media-centre",
    "media-center",
    "newsroom"

]

candidate_links = []

for link in all_links:

    lower = link.lower()

    if any(keyword in lower for keyword in ARTICLE_KEYWORDS):

        candidate_links.append(link)

print(f"Candidate governance pages: {len(candidate_links)}")

Candidate governance pages: 409

**REMOVE DUPLICATES**

In [9]:
# ============================================================
# CELL 7: REMOVE DUPLICATES
# ============================================================

candidate_links = list(set(candidate_links))

candidate_links = [

    url for url in candidate_links

    if url.startswith("http")

]

candidate_links.sort()

print(f"Unique links: {len(candidate_links)}")

Unique links: 170

**DOWNLOAD ARTICLES**

In [10]:
# ============================================================
# CELL 8: DOWNLOAD ARTICLES
# ============================================================

raw_articles = []

for url in tqdm(candidate_links):

    soup = fetch_page(url)

    if soup is None:
        continue

    title = ""

    if soup.title:
        title = soup.title.get_text(strip=True)

    paragraphs = soup.find_all("p")

    text = " ".join(

        p.get_text(" ", strip=True)

        for p in paragraphs

    )

    if len(text) < 200:
        continue

    raw_articles.append({

        "url": url,

        "title": title,

        "text": text

    })

print(f"Articles collected: {len(raw_articles)}")

 22%|██▏       | 37/170 [03:19<10:19,  4.66s/it]

Failed: https://www.eacc.go.ke/news-updates
404 Client Error: Not Found for url: https://www.eacc.go.ke/news-updates

 24%|██▎       | 40/170 [03:58<26:53, 12.41s/it]

Failed: https://www.ecitizen.go.ke/en/
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Read timed out. (read timeout=30)

 26%|██▋       | 45/170 [04:57<28:15, 13.56s/it]

Failed: https://www.ecitizen.go.ke/en/login
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 30%|███       | 51/170 [06:45<43:59, 22.18s/it]

Failed: https://www.ecitizen.go.ke/get-business?business=0
HTTPSConnectionPool(host='accounts.ecitizen.go.ke', port=443): Read timed out.

 34%|███▍      | 58/170 [08:49<39:32, 21.18s/it]

Failed: https://www.health.go.ke/publications
HTTPSConnectionPool(host='www.health.go.ke', port=443): Read timed out. (read timeout=30)

 40%|████      | 68/170 [1:39:11<24:24:17, 861.35s/it]

Failed: https://www.iebc.or.ke/news/?Press_Release_-__Update_on_Preparedness_for_the_16th_July_2026_Ol_Kalou_By-Election
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /news/?Press_Release_-__Update_on_Preparedness_for_the_16th_July_2026_Ol_Kalou_By-Election (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F94C6018D0>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))

Failed: https://www.iebc.or.ke/resources/?Publications_/_Reports
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /resources/?Publications_/_Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601210>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FC810>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1252/KNCHR-Advisory-on-Fraudulent-Compensation-and-Reparations-Claims
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1252/KNCHR-Advisory-on-Fraudulent-Compensation-and-Reparations-Claims (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FD250>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1253/Statement-on-Human-Rights-Concerns-During-Today%e2%80%99s-Fuel-Strike
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1253/Statement-on-Human-Rights-Concerns-During-Today%E2%80%99s-Fuel-Strike (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06CA90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

 49%|████▉     | 84/170 [1:39:11<2:34:55, 108.08s/it]

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1254/Condolence-Message-following-the-Tragic-Fire-at-Utumishi-Girls-Academy-Gilgil
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1254/Condolence-Message-following-the-Tragic-Fire-at-Utumishi-Girls-Academy-Gilgil (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E590>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1256/REMARKS-BY-MS-CLARIS-OGANGAH-CHAIRPERSON-KENYA-NATIONAL-COMMISSION-ON-HUMAN-RIGHTS-KNCHR-DURING-THE-PRESENTATION-OF-THE-NATIONAL-REPARATIONS-FRAMEWORK-AND-REPORT-TO-THE-PRESIDENT-OF-THE-REPUBLIC
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1256/REMARKS-BY-MS-CLARIS-OGANGAH-CHAIRPERSON-KENYA-NATIONAL-COMMISSION-ON-HUMAN-RIGHTS-KNCHR-DURING-THE-PRESENTATION-OF-THE-NATIONAL-REPARATIONS-FRAMEWORK-AND-REPORT-TO-THE-PRESIDENT-OF-THE-REPUBLIC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63F750>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1257/Attacks-on-Places-of-Worship-is-a-Violation-of-Freedom-of-Worship-and-Assembly
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1257/Attacks-on-Places-of-Worship-is-a-Violation-of-Freedom-of-Worship-and-Assembly (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06CDD0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1258/Enforced-Disappearances-Torture-and-other-Human-Rights-Violations-following-the-25th-June-2026-Protests-Marking-the-2nd-Anniversary-of-the-2024-Gen-Z-Protests
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1258/Enforced-Disappearances-Torture-and-other-Human-Rights-Violations-following-the-25th-June-2026-Protests-Marking-the-2nd-Anniversary-of-the-2024-Gen-Z-Protests (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FC950>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1259/KNCHR-CONDEMNS-ESCALATING-POLITICAL-VIOLENCE-AND-ELECTORAL-MALPRACTICES-DURING-THE-OL-KALOU-CONSTITUENCY-BY-ELECTION-CAMPAIGNS
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1259/KNCHR-CONDEMNS-ESCALATING-POLITICAL-VIOLENCE-AND-ELECTORAL-MALPRACTICES-DURING-THE-OL-KALOU-CONSTITUENCY-BY-ELECTION-CAMPAIGNS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FE2D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/E-Newsletter
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/E-Newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601450>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Gallery
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Gallery (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63FF50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/KNCHR-Draft-Regulations-2025
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/KNCHR-Draft-Regulations-2025 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C410>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Press-Statements
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Press-Statements (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C390>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Tenders
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Tenders (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63FA50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Curriculum-and-Training-Manual-Development
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Curriculum-and-Training-Manual-Development (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C6026D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Public-Awareness-Programmes
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Public-Awareness-Programmes (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FE610>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Trainings
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Trainings (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FEF90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Portals/0/Articles/KenyaNationalCommissiononHumanRights_Act_No14of2011.pdf?ver=2016-08-01-132051-907
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Portals/0/Articles/KenyaNationalCommissiononHumanRights_Act_No14of2011.pdf?ver=2016-08-01-132051-907 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E2D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Advisories
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Advisories (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FF010>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Annual-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Annual-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FD190>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Commission-Exit-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Commission-Exit-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06CC10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Corruption-and-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Corruption-and-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603F10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/General
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/General (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C6D10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/International-Obligation
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/International-Obligation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C750>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/National-Values-Principles-of-Governance
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/National-Values-Principles-of-Governance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DEB10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Nguzo-za-Haki
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Nguzo-za-Haki (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63CE10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Occassional
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Occassional (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06CE10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

 64%|██████▎   | 108/170 [1:39:12<32:58, 31.91s/it]

Failed: https://www.knchr.org/Publications/Relevant-Publications
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Relevant-Publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C600650>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Relevant-Publications/Publications-Catalogue-Summary
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Relevant-Publications/Publications-Catalogue-Summary (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FE0D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Service-Charter
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Service-Charter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FED90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/State-of-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/State-of-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF450>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Strategic-Plan
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Strategic-Plan (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FC210>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Access-to-Justice
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Access-to-Justice (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDB90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Election-Related-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Election-Related-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603ED0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Freedom-of-Association
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Freedom-of-Association (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06DF90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Prison-Reforms
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Prison-Reforms (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD390>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Security-Sector
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Security-Sector (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C7290>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Torture-Extrajudicial-Executions-Enforced-Disappearance
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Torture-Extrajudicial-Executions-Enforced-Disappearance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51FA90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Business-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Business-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C7350>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Climate-Change-and-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Climate-Change-and-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63D590>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-To-Water
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-To-Water (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C6037D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Adequate-Housing
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Adequate-Housing (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE350>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Education
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Education (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FD6D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Health
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Health (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F250>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Children-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Children-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601B10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Indigenous-Peoples-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Indigenous-Peoples-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE190>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Intersex-Persons
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Intersex-Persons (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DFF50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

 78%|███████▊  | 132/170 [1:39:12<08:08, 12.86s/it]

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Migrants
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Migrants (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FF0D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Older-Persons
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Older-Persons (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63D710>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Persons-with-Disability-PWD
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Persons-with-Disability-PWD (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F650>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Womens-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Womens-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E090>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/component/publications/publications
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /component/publications/publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63D510>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/images/publications/ALTERNATIVE-DISPUTE-RESOLUTION-APPLICATION-BY-THE-TAXPAYER-2025.docx
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /images/publications/ALTERNATIVE-DISPUTE-RESOLUTION-APPLICATION-BY-THE-TAXPAYER-2025.docx (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC4D0>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/images/publications/KRA-Information-Security-Policy.pdf
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /images/publications/KRA-Information-Security-Policy.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDD10>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FCDD0>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2376-removal-of-excise-duty-on-bottled-water
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2376-removal-of-excise-duty-on-bottled-water (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603850>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2379-fringe-benefit-tax,-deemed-interest-rate-and-low-interest-benefit-7
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2379-fringe-benefit-tax,-deemed-interest-rate-and-low-interest-benefit-7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F2D0>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2380-advance-cargo-declaration-acd-platform-for-containerized-cargo
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2380-advance-cargo-declaration-acd-platform-for-containerized-cargo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C6037D0>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/publications
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC3D0>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/communication-information-innovation
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/communication-information-innovation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC850>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-accounts-committee
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-accounts-committee (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63F150>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-debt-privatization
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-debt-privatization (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51DAD0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-investments-committee-on-governance-education
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-investments-committee-on-governance-education (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDB50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-investments-committee-on-social-services-administration-agriculture
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-investments-committee-on-social-services-administration-agriculture (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF390>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-petitions-committee
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-petitions-committee (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63EED0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/transport-public-works-housing
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/transport-public-works-housing (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C6A50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/media-rules-and-filming
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /media-rules-and-filming (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF810>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/national-assembly-e-newsletter
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /national-assembly-e-newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D6D0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-national-assembly/news-events
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-national-assembly/news-events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603950>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-senate/e-newsletter
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-senate/e-newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601E50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-senate/news-events
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-senate/news-events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FE1D0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDD10>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

 92%|█████████▏| 157/170 [1:39:12<01:14,  5.70s/it]

Failed: https://www.publicservice.go.ke/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51E690>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/#ekit_modal-popup-2d11ac0
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D390>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/#ekit_modal-popup-a97a2a8
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE510>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/circulars/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /circulars/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DEA90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/commission-mandate/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /commission-mandate/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF0D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/communication-strategy/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /communication-strategy/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC2D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/contact/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /contact/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51C490>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/discussion-forum/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /discussion-forum/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51DE10>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/forms/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /forms/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FE110>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/frequently-asked-questions/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /frequently-asked-questions/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C6FD0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/internship/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /internship/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63F250>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/jobs/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /jobs/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51FE50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/legislation
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /legislation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51FB10>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/news-updates/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /news-updates/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D0D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/newsletters/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /newsletters/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FC690>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/partner-with-us
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /partner-with-us (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C310>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/photo-gallery/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /photo-gallery/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF790>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/policies-and-guidelines/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /policies-and-guidelines/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE5D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/press-releases/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /press-releases/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FEB90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/promotional-exams/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /promotional-exams/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FC950>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-sha-consult-on-deployment-of-former-nhif-officers-to-mdas/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-sha-consult-on-deployment-of-former-nhif-officers-to-mdas/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F590>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-sightsavers-partner-to-enhance-disability-mainstreaming-in-the-public-service/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-sightsavers-partner-to-enhance-disability-mainstreaming-in-the-public-service/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51FA90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-to-launch-nationwide-sensitization-on-national-values-and-principles-of-public-service/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-to-launch-nationwide-sensitization-on-national-values-and-principles-of-public-service/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C210>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

100%|██████████| 170/170 [1:39:12<00:00, 35.02s/it]

Failed: https://www.publicservice.go.ke/report-corruption/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /report-corruption/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C602F50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/reports/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /reports/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D310>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/speeches/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /speeches/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51CB50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/strategic-plan/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /strategic-plan/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FEC50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/tenders/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /tenders/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C650>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/the-commission/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /the-commission/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC690>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/the-secretariat/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /the-secretariat/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF590>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/values-principles-reports
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /values-principles-reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC610>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/wp-content/uploads/2025/08/PSC-Citizen-Service-Charter-EXTERNAL.pdf
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /wp-content/uploads/2025/08/PSC-Citizen-Service-Charter-EXTERNAL.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DFD90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))
Articles collected: 35

**SCRAPE EVERY DISCOVERED PAGE**

In [11]:
# ============================================================
# CELL 9: SCRAPE EVERY DISCOVERED PAGE
# ============================================================

raw_articles = []

for url in tqdm(candidate_links):

    soup = fetch_page(url)

    if soup is None:
        continue

    # ---------------------------
    # Get Title
    # ---------------------------

    if soup.title:
        title = soup.title.get_text(strip=True)
    else:
        title = ""

    # ---------------------------
    # Get Meta Description
    # ---------------------------

    description = ""

    meta = soup.find("meta", attrs={"name":"description"})

    if meta:
        description = meta.get("content","")

    # ---------------------------
    # Extract Paragraphs
    # ---------------------------

    paragraphs = soup.find_all("p")

    text = " ".join(

        p.get_text(" ", strip=True)

        for p in paragraphs

    )

    if len(text) < 150:

        continue

    raw_articles.append({

        "url": url,

        "title": title,

        "description": description,

        "text": text

    })

print()

print("Articles collected:", len(raw_articles))

 16%|█▌        | 27/170 [00:00<00:01, 132.50it/s]

Failed: http://publicservice.go.ke/about-us/
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /about-us/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94C603550>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: http://publicservice.go.ke/jobs/
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /jobs/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94D0DF490>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: http://publicservice.go.ke/news-updates/
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /news-updates/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94E06CD10>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: http://publicservice.go.ke/partner-with-us
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /partner-with-us (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94D5B2090>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: http://publicservice.go.ke/programmes/
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /programmes/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94D5B2FD0>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: http://publicservice.go.ke/resources/
HTTPConnectionPool(host='publicservice.go.ke', port=80): Max retries exceeded with url: /resources/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001F94B9AA510>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://accounts.ecitizen.go.ke/en
HTTPSConnectionPool(host='accounts.ecitizen.go.ke', port=443): Max retries exceeded with url: /en (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0E90>: Failed to resolve 'accounts.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://dis.ecitizen.go.ke/
HTTPSConnectionPool(host='dis.ecitizen.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1410>: Failed to resolve 'dis.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eCitizen.go.ke
HTTPSConnectionPool(host='ecitizen.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1050>: Failed to resolve 'ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eacc.go.ke/en/default/feed/eacc-and-bungoma-county-leadership-unite-to-champion-integrity-in-public-service
HTTPSConnectionPool(host='eacc.go.ke', port=443): Max retries exceeded with url: /en/default/feed/eacc-and-bungoma-county-leadership-unite-to-champion-integrity-in-public-service (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE1D0>: Failed to resolve 'eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eacc.go.ke/en/default/feed/two-public-officers-arrested-for-diversion-of-county-revenue
HTTPSConnectionPool(host='eacc.go.ke', port=443): Max retries exceeded with url: /en/default/feed/two-public-officers-arrested-for-diversion-of-county-revenue (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E110>: Failed to resolve 'eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eacc.go.ke/en/default/news-updates/
HTTPSConnectionPool(host='eacc.go.ke', port=443): Max retries exceeded with url: /en/default/news-updates/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C600AD0>: Failed to resolve 'eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eacc.go.ke/en/default/newsletter-2/
HTTPSConnectionPool(host='eacc.go.ke', port=443): Max retries exceeded with url: /en/default/newsletter-2/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDE50>: Failed to resolve 'eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://eacc.go.ke/en/default/speeches/
HTTPSConnectionPool(host='eacc.go.ke', port=443): Max retries exceeded with url: /en/default/speeches/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06F5D0>: Failed to resolve 'eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://ecitizen.go.ke
HTTPSConnectionPool(host='ecitizen.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD350>: Failed to resolve 'ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://immigration.go.ke/articles/
HTTPSConnectionPool(host='immigration.go.ke', port=443): Max retries exceeded with url: /articles/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603150>: Failed to resolve 'immigration.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://immigration.go.ke/citizenship-section/
HTTPSConnectionPool(host='immigration.go.ke', port=443): Max retries exceeded with url: /citizenship-section/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1650>: Failed to resolve 'immigration.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://immigration.go.ke/status-update-on-issuance-of-national-id-card/
HTTPSConnectionPool(host='immigration.go.ke', port=443): Max retries exceeded with url: /status-update-on-issuance-of-national-id-card/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3A10>: Failed to resolve 'immigration.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://ke.linkedin.com/company/public-service-commission-kenya
HTTPSConnectionPool(host='ke.linkedin.com', port=443): Max retries exceeded with url: /company/public-service-commission-kenya (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A89D0>: Failed to resolve 'ke.linkedin.com' ([Errno 11001] getaddrinfo failed)"))

Failed: https://kra.go.ke/images/publications/New-Income-Tax-Exemptions-Application-Form.pdf
HTTPSConnectionPool(host='kra.go.ke', port=443): Max retries exceeded with url: /images/publications/New-Income-Tax-Exemptions-Application-Form.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0390>: Failed to resolve 'kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://kra.go.ke/images/publications/Passenger-Declaration-Form-May-2018-Editable.pdf
HTTPSConnectionPool(host='kra.go.ke', port=443): Max retries exceeded with url: /images/publications/Passenger-Declaration-Form-May-2018-Editable.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2B50>: Failed to resolve 'kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://kra.go.ke/images/publications/Requirements-for-Licensing-Excisbale-Goods-Manufacturers.pdf
HTTPSConnectionPool(host='kra.go.ke', port=443): Max retries exceeded with url: /images/publications/Requirements-for-Licensing-Excisbale-Goods-Manufacturers.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B00D0>: Failed to resolve 'kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://kra.go.ke/images/publications/Requirements-for-Registration--Importers-of-Excisable-goods.pdf
HTTPSConnectionPool(host='kra.go.ke', port=443): Max retries exceeded with url: /images/publications/Requirements-for-Registration--Importers-of-Excisable-goods.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC190>: Failed to resolve 'kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://kra.go.ke/images/publications/The-9th-Corporate-Plan.pdf
HTTPSConnectionPool(host='kra.go.ke', port=443): Max retries exceeded with url: /images/publications/The-9th-Corporate-Plan.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E5D0>: Failed to resolve 'kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://odpp.go.ke/news-updates/
HTTPSConnectionPool(host='odpp.go.ke', port=443): Max retries exceeded with url: /news-updates/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FD950>: Failed to resolve 'odpp.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://odpp.go.ke/newsletters/
HTTPSConnectionPool(host='odpp.go.ke', port=443): Max retries exceeded with url: /newsletters/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FCC90>: Failed to resolve 'odpp.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://odpp.go.ke/press-statements/
HTTPSConnectionPool(host='odpp.go.ke', port=443): Max retries exceeded with url: /press-statements/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06F790>: Failed to resolve 'odpp.go.ke' ([Errno 11001] getaddrinfo failed)"))

 24%|██▍       | 41/170 [00:00<00:01, 118.09it/s]

Failed: https://parliament.go.ke/index.php/invitation-submit-memoranda-notification-public-hearings-matter-consideration-national-assembly
HTTPSConnectionPool(host='parliament.go.ke', port=443): Max retries exceeded with url: /index.php/invitation-submit-memoranda-notification-public-hearings-matter-consideration-national-assembly (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF7D0>: Failed to resolve 'parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://parliament.go.ke/invitation-submit-memoranda-notification-public-hearings-matter-consideration-national-assembly
HTTPSConnectionPool(host='parliament.go.ke', port=443): Max retries exceeded with url: /invitation-submit-memoranda-notification-public-hearings-matter-consideration-national-assembly (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B27C750>: Failed to resolve 'parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://pscims.publicservice.go.ke/jobs/
HTTPSConnectionPool(host='pscims.publicservice.go.ke', port=443): Max retries exceeded with url: /jobs/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1110>: Failed to resolve 'pscims.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://pscims.publicservice.go.ke/jobs/loginPage.aspx
HTTPSConnectionPool(host='pscims.publicservice.go.ke', port=443): Max retries exceeded with url: /jobs/loginPage.aspx (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B03D0>: Failed to resolve 'pscims.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://publicservice.go.ke
HTTPSConnectionPool(host='publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A8CD0>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://publicservice.go.ke/
HTTPSConnectionPool(host='publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1610>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://publicservice.go.ke/about-us/
HTTPSConnectionPool(host='publicservice.go.ke', port=443): Max retries exceeded with url: /about-us/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1190>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://publicservice.go.ke/frequently-asked-questions/
HTTPSConnectionPool(host='publicservice.go.ke', port=443): Max retries exceeded with url: /frequently-asked-questions/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0690>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://publicservice.go.ke/mdas/
HTTPSConnectionPool(host='publicservice.go.ke', port=443): Max retries exceeded with url: /mdas/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DEC90>: Failed to resolve 'publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.eacc.go.ke/news-updates
HTTPSConnectionPool(host='www.eacc.go.ke', port=443): Max retries exceeded with url: /news-updates (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E2D0>: Failed to resolve 'www.eacc.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/#main-content
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FDD10>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F310>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1A90>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/counties
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/counties (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B19D0>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/help-and-support
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/help-and-support (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06FCD0>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/home/counties
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/home/counties (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DCA90>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/home/national-ministries
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/home/national-ministries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603F50>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/login
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/login (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63FA50>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/ministries
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/ministries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C600B10>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/privacy-policy
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/privacy-policy (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3290>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

 38%|███▊      | 65/170 [00:00<00:00, 116.36it/s]

Failed: https://www.ecitizen.go.ke/en/profile/documents/national-id
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/profile/documents/national-id (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3650>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/register
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/register (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DC4D0>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/en/terms-and-conditions
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /en/terms-and-conditions (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FFAD0>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/get-business?business=0
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /get-business?business=0 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63DC50>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.ecitizen.go.ke/sw
HTTPSConnectionPool(host='www.ecitizen.go.ke', port=443): Max retries exceeded with url: /sw (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06DE90>: Failed to resolve 'www.ecitizen.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/events
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FEED0>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/moh-weekly-news
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /moh-weekly-news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD250>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/newsletter
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1C90>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/press-statements
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /press-statements (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3E10>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/ps-mary-muthoni-rallies-health-regulators-strengthen-coordination-and-public-health-oversight
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /ps-mary-muthoni-rallies-health-regulators-strengthen-coordination-and-public-health-oversight (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601290>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.health.go.ke/publications
HTTPSConnectionPool(host='www.health.go.ke', port=443): Max retries exceeded with url: /publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AAF50>: Failed to resolve 'www.health.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/electionlaws/?Gazette_Notices
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /electionlaws/?Gazette_Notices (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603290>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/media/?news
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /media/?news (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3290>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/media/?press
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /media/?press (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0AD0>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/media/?speeches
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /media/?speeches (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DEB10>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/news/?IEBC,_HURIA_Explore_Partnership_to_Strengthen_Voter_Education_and_Youth_Civic_Participation
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /news/?IEBC,_HURIA_Explore_Partnership_to_Strengthen_Voter_Education_and_Youth_Civic_Participation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51EED0>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/news/?IEBC_Electoral_Code_Committee_Finds_Nakuru_Town_East_MP_Guilty_of_Code_of_Conduct_Breach
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /news/?IEBC_Electoral_Code_Committee_Finds_Nakuru_Town_East_MP_Guilty_of_Code_of_Conduct_Breach (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06DE90>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/news/?JUDGEMENT:
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /news/?JUDGEMENT: (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E910>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/news/?Press_Release_-__Update_on_Preparedness_for_the_16th_July_2026_Ol_Kalou_By-Election
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /news/?Press_Release_-__Update_on_Preparedness_for_the_16th_July_2026_Ol_Kalou_By-Election (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63EE10>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.iebc.or.ke/resources/?Publications_/_Reports
HTTPSConnectionPool(host='www.iebc.or.ke', port=443): Max retries exceeded with url: /resources/?Publications_/_Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51CA90>: Failed to resolve 'www.iebc.or.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3F10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1252/KNCHR-Advisory-on-Fraudulent-Compensation-and-Reparations-Claims
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1252/KNCHR-Advisory-on-Fraudulent-Compensation-and-Reparations-Claims (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603390>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1253/Statement-on-Human-Rights-Concerns-During-Today%e2%80%99s-Fuel-Strike
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1253/Statement-on-Human-Rights-Concerns-During-Today%E2%80%99s-Fuel-Strike (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DDAD0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1254/Condolence-Message-following-the-Tragic-Fire-at-Utumishi-Girls-Academy-Gilgil
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1254/Condolence-Message-following-the-Tragic-Fire-at-Utumishi-Girls-Academy-Gilgil (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A9850>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1256/REMARKS-BY-MS-CLARIS-OGANGAH-CHAIRPERSON-KENYA-NATIONAL-COMMISSION-ON-HUMAN-RIGHTS-KNCHR-DURING-THE-PRESENTATION-OF-THE-NATIONAL-REPARATIONS-FRAMEWORK-AND-REPORT-TO-THE-PRESIDENT-OF-THE-REPUBLIC
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1256/REMARKS-BY-MS-CLARIS-OGANGAH-CHAIRPERSON-KENYA-NATIONAL-COMMISSION-ON-HUMAN-RIGHTS-KNCHR-DURING-THE-PRESENTATION-OF-THE-NATIONAL-REPARATIONS-FRAMEWORK-AND-REPORT-TO-THE-PRESIDENT-OF-THE-REPUBLIC (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2BD0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1257/Attacks-on-Places-of-Worship-is-a-Violation-of-Freedom-of-Worship-and-Assembly
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1257/Attacks-on-Places-of-Worship-is-a-Violation-of-Freedom-of-Worship-and-Assembly (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1410>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1258/Enforced-Disappearances-Torture-and-other-Human-Rights-Violations-following-the-25th-June-2026-Protests-Marking-the-2nd-Anniversary-of-the-2024-Gen-Z-Protests
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1258/Enforced-Disappearances-Torture-and-other-Human-Rights-Violations-following-the-25th-June-2026-Protests-Marking-the-2nd-Anniversary-of-the-2024-Gen-Z-Protests (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51DB10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

 55%|█████▍    | 93/170 [00:00<00:00, 126.46it/s]

Failed: https://www.knchr.org/Articles/ArtMID/2432/ArticleID/1259/KNCHR-CONDEMNS-ESCALATING-POLITICAL-VIOLENCE-AND-ELECTORAL-MALPRACTICES-DURING-THE-OL-KALOU-CONSTITUENCY-BY-ELECTION-CAMPAIGNS
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Articles/ArtMID/2432/ArticleID/1259/KNCHR-CONDEMNS-ESCALATING-POLITICAL-VIOLENCE-AND-ELECTORAL-MALPRACTICES-DURING-THE-OL-KALOU-CONSTITUENCY-BY-ELECTION-CAMPAIGNS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE510>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/E-Newsletter
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/E-Newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF710>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Gallery
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Gallery (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06D650>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/KNCHR-Draft-Regulations-2025
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/KNCHR-Draft-Regulations-2025 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601350>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Press-Statements
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Press-Statements (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06F110>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/News-Room/Tenders
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /News-Room/Tenders (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63E250>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Curriculum-and-Training-Manual-Development
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Curriculum-and-Training-Manual-Development (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0F50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Public-Awareness-Programmes
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Public-Awareness-Programmes (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2290>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Our-Work/Public-Education-and-Training/Trainings
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Our-Work/Public-Education-and-Training/Trainings (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF090>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Portals/0/Articles/KenyaNationalCommissiononHumanRights_Act_No14of2011.pdf?ver=2016-08-01-132051-907
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Portals/0/Articles/KenyaNationalCommissiononHumanRights_Act_No14of2011.pdf?ver=2016-08-01-132051-907 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A8850>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Advisories
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Advisories (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0DD0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Annual-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Annual-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2150>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Commission-Exit-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Commission-Exit-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63D8D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Corruption-and-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Corruption-and-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE190>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/General
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/General (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06C950>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/International-Obligation
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/International-Obligation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C602A10>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/National-Values-Principles-of-Governance
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/National-Values-Principles-of-Governance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C601350>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Nguzo-za-Haki
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Nguzo-za-Haki (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF390>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Occassional
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Occassional (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF090>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Relevant-Publications
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Relevant-Publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63D5D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Relevant-Publications/Publications-Catalogue-Summary
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Relevant-Publications/Publications-Catalogue-Summary (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0090>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Service-Charter
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Service-Charter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0490>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/State-of-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/State-of-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A9890>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Strategic-Plan
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Strategic-Plan (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2690>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Access-to-Justice
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Access-to-Justice (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B06D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Election-Related-Reports
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Election-Related-Reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63CC50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Freedom-of-Association
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Freedom-of-Association (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD110>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

 71%|███████   | 120/170 [00:00<00:00, 127.69it/s]

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Prison-Reforms
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Prison-Reforms (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06FBD0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Security-Sector
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Security-Sector (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C6013D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Civil-and-Political-Rights/Torture-Extrajudicial-Executions-Enforced-Disappearance
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Civil-and-Political-Rights/Torture-Extrajudicial-Executions-Enforced-Disappearance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94962E290>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Business-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Business-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD010>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Climate-Change-and-Human-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Climate-Change-and-Human-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF610>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-To-Water
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-To-Water (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63E990>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Adequate-Housing
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Adequate-Housing (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2C90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Education
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Education (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1C50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Health
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Ecosoc-Rights/Right-to-Health (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AA9D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Children-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Children-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63CD90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Indigenous-Peoples-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Indigenous-Peoples-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D710>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Intersex-Persons
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Intersex-Persons (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1050>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Migrants
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Migrants (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DFC90>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Older-Persons
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Older-Persons (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603810>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Rights-of-Persons-with-Disability-PWD
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Rights-of-Persons-with-Disability-PWD (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C6E50>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.knchr.org/Publications/Thematic-Reports/Group-Rights/Womens-Rights
HTTPSConnectionPool(host='www.knchr.org', port=443): Max retries exceeded with url: /Publications/Thematic-Reports/Group-Rights/Womens-Rights (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94E06E3D0>: Failed to resolve 'www.knchr.org' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/component/publications/publications
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /component/publications/publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DCA50>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/images/publications/ALTERNATIVE-DISPUTE-RESOLUTION-APPLICATION-BY-THE-TAXPAYER-2025.docx
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /images/publications/ALTERNATIVE-DISPUTE-RESOLUTION-APPLICATION-BY-THE-TAXPAYER-2025.docx (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C6910>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/images/publications/KRA-Information-Security-Policy.pdf
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /images/publications/KRA-Information-Security-Policy.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63FC10>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1610>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2376-removal-of-excise-duty-on-bottled-water
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2376-removal-of-excise-duty-on-bottled-water (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FD610>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2379-fringe-benefit-tax,-deemed-interest-rate-and-low-interest-benefit-7
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2379-fringe-benefit-tax,-deemed-interest-rate-and-low-interest-benefit-7 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A9D50>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/news-center/public-notices/2380-advance-cargo-declaration-acd-platform-for-containerized-cargo
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /news-center/public-notices/2380-advance-cargo-declaration-acd-platform-for-containerized-cargo (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603010>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.kra.go.ke/publications
HTTPSConnectionPool(host='www.kra.go.ke', port=443): Max retries exceeded with url: /publications (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0450>: Failed to resolve 'www.kra.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/communication-information-innovation
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/communication-information-innovation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2810>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-accounts-committee
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-accounts-committee (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D7C74D0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

 86%|████████▌ | 146/170 [00:01<00:00, 114.19it/s]

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-debt-privatization
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-debt-privatization (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DF350>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-investments-committee-on-governance-education
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-investments-committee-on-governance-education (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A8E50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-investments-committee-on-social-services-administration-agriculture
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-investments-committee-on-social-services-administration-agriculture (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51F1D0>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/public-petitions-committee
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/public-petitions-committee (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DDE50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/index.php/the-national-assembly/committees/12/transport-public-works-housing
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /index.php/the-national-assembly/committees/12/transport-public-works-housing (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63F350>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/media-rules-and-filming
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /media-rules-and-filming (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2150>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/national-assembly-e-newsletter
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /national-assembly-e-newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B3D50>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-national-assembly/news-events
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-national-assembly/news-events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A9510>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-senate/e-newsletter
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-senate/e-newsletter (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FF290>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.parliament.go.ke/the-senate/news-events
HTTPSConnectionPool(host='www.parliament.go.ke', port=443): Max retries exceeded with url: /the-senate/news-events (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2210>: Failed to resolve 'www.parliament.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1C90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C602A10>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/#ekit_modal-popup-2d11ac0
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D963050>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/#ekit_modal-popup-a97a2a8
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DFDD0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/circulars/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /circulars/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AB710>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/commission-mandate/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /commission-mandate/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DE490>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/communication-strategy/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /communication-strategy/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DD1D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/contact/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /contact/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63CD90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/discussion-forum/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /discussion-forum/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AAE90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/forms/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /forms/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C5FF290>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/frequently-asked-questions/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /frequently-asked-questions/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0D90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/internship/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /internship/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51D610>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/jobs/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /jobs/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63DB50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/legislation
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /legislation (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94DCFF410>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/news-updates/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /news-updates/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1C50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

100%|██████████| 170/170 [00:01<00:00, 121.61it/s]

Failed: https://www.publicservice.go.ke/newsletters/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /newsletters/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A8B90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/partner-with-us
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /partner-with-us (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AA6D0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/photo-gallery/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /photo-gallery/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C602310>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/policies-and-guidelines/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /policies-and-guidelines/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C603B90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/press-releases/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /press-releases/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51EED0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/promotional-exams/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /promotional-exams/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B1210>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-sha-consult-on-deployment-of-former-nhif-officers-to-mdas/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-sha-consult-on-deployment-of-former-nhif-officers-to-mdas/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2550>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-sightsavers-partner-to-enhance-disability-mainstreaming-in-the-public-service/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-sightsavers-partner-to-enhance-disability-mainstreaming-in-the-public-service/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9A8E90>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/psc-to-launch-nationwide-sensitization-on-national-values-and-principles-of-public-service/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /psc-to-launch-nationwide-sensitization-on-national-values-and-principles-of-public-service/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AA810>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/report-corruption/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /report-corruption/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D0DEC50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/reports/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /reports/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94C63C490>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/speeches/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /speeches/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AB050>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/strategic-plan/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /strategic-plan/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94B9AB110>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/tenders/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /tenders/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D51C590>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/the-commission/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /the-commission/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B0350>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/the-secretariat/
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /the-secretariat/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2890>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/values-principles-reports
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /values-principles-reports (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2FD0>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Failed: https://www.publicservice.go.ke/wp-content/uploads/2025/08/PSC-Citizen-Service-Charter-EXTERNAL.pdf
HTTPSConnectionPool(host='www.publicservice.go.ke', port=443): Max retries exceeded with url: /wp-content/uploads/2025/08/PSC-Citizen-Service-Charter-EXTERNAL.pdf (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F94D5B2A50>: Failed to resolve 'www.publicservice.go.ke' ([Errno 11001] getaddrinfo failed)"))

Articles collected: 0

**Create a Dataframe**

In [12]:
# ============================================================
# CELL 10: CREATE DATAFRAME
# ============================================================

df = pd.DataFrame(raw_articles)

print(df.shape)

df.head()

(0, 0)

Empty DataFrame
Columns: []
Index: []

**REMOVE DUPLICATES**

In [13]:
# ============================================================
# CELL 11: REMOVE DUPLICATES
# ============================================================

df.drop_duplicates(
    subset=["url"],
    inplace=True
)

df.drop_duplicates(
    subset=["text"],
    inplace=True
)

df.reset_index(drop=True, inplace=True)

print("Remaining articles:", len(df))

Remaining articles: 0

**Clean Article Text**

In [14]:
# ============================================================
# CELL 12: CLEAN ARTICLE TEXT
# ============================================================

def clean_text(text):

    text = re.sub(r"\s+", " ", text)

    text = text.strip()

    return text

df["text"] = df["text"].apply(clean_text)

df["title"] = df["title"].apply(clean_text)

df["description"] = df["description"].fillna("").apply(clean_text)

print(df.head())

KeyError: 'text'

**INSTALL TRAFILATURA**

In [ ]:
# ============================================================
# CELL 13: INSTALL TRAFILATURA
# ============================================================

%pip install trafilatura

Collecting trafilaturaNote: you may need to restart the kernel to use updated packages.

  Using cached trafilatura-2.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: certifi in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from trafilatura) (2023.7.22)
Collecting charset_normalizer>=3.4.0 (from trafilatura)
  Downloading charset_normalizer-3.4.9-cp311-cp311-win_amd64.whl.metadata (42 kB)
Collecting courlan>=1.4.0 (from trafilatura)
  Using cached courlan-1.4.0-py3-none-any.whl.metadata (18 kB)
Collecting htmldate>=1.10.0 (from trafilatura)
  Using cached htmldate-1.10.0-py3-none-any.whl.metadata (9.8 kB)
Collecting justext>=3.0.2 (from trafilatura)
  Using cached justext-3.0.2-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting lxml>=6.1.1 (from trafilatura)
  Downloading lxml-6.1.1-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from trafilatura) (2.0.5)
Collecting babel>=2.16.0 (from courlan>=1.4.0->trafilatura)
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting tld>=0.13 (from courlan>=1.4.0->trafilatura)
  Using cached tld-0.13.2-py2.py3-none-any.whl.metadata (11 kB)
Collecting dateparser>=1.1.2 (from htmldate>=1.10.0->trafilatura)
  Using cached dateparser-1.4.1-py3-none-any.whl.metadata (22 kB)
Collecting python-dateutil>=2.9.0.post0 (from htmldate>=1.10.0->trafilatura)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2024.2 (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting regex>=2024.9.11 (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura)
  Downloading regex-2026.7.10-cp311-cp311-win_amd64.whl.metadata (41 kB)
Collecting tzlocal>=0.2 (from dateparser>=1.1.2->htmldate>=1.10.0->trafilatura)
  Using cached tzlocal-5.4.4-py3-none-any.whl.metadata (7.7 kB)
Collecting lxml_html_clean (from lxml[html_clean]>=4.4.2->justext>=3.0.2->trafilatura)
  Using cached lxml_html_clean-0.4.5-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: six>=1.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.9.0.post0->htmldate>=1.10.0->trafilatura) (1.16.0)
Requirement already satisfied: tzdata in C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages (from tzlocal>=0.2->dateparser>=1.1.2->htmldate>=1.10.0->trafilatura) (2023.3)
Using cached trafilatura-2.1.0-py3-none-any.whl (134 kB)
Downloading charset_normalizer-3.4.9-cp311-cp311-win_amd64.whl (161 kB)
Using cached courlan-1.4.0-py3-none-any.whl (34 kB)
Using cached babel-2.18.0-py3-none-any.whl (10.2 MB)
Using cached htmldate-1.10.0-py3-none-any.whl (31 kB)
Using cached dateparser-1.4.1-py3-none-any.whl (300 kB)
Using cached justext-3.0.2-py2.py3-none-any.whl (837 kB)
Downloading lxml-6.1.1-cp311-cp311-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ------- -------------------------------- 0.8/4.0 MB 2.8 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.3 MB/s  0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Downloading regex-2026.7.10-cp311-cp311-win_amd64.whl (277 kB)
Using cached tld-0.13.2-py2.py3-none-any.whl (296 kB)
Using cached tzlocal-5.4.4-py3-none-any.whl (18 kB)
Using cached lxml_html_clean-0.4.5-py3-none-any.whl (14 kB)
Installing collected packages: pytz, tzlocal, tld, regex, python-dateutil, lxml, charset_normalizer, babel, lxml_html_clean, dateparser, courlan, htmldate, justext, trafilatura

  Attempting uninstall: pytz

    Found existing installation: pytz 2023.3.post1

   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
    Uninstalling pytz-2023.3.post1:
   ----------------------------------------  0/14 [pytz]
      Successfully uninstalled pytz-2023.3.post1
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   ----------------------------------------  0/14 [pytz]
   -- -------------------------------------  1/14 [tzlocal]
   ----- ----------------------------------  2/14 [tld]
   ----- ----------------------------------  2/14 [tld]
   ----- ----------------------------------  2/14 [tld]
  Attempting uninstall: regex
   ----- ----------------------------------  2/14 [tld]
    Found existing installation: regex 2023.10.3
   ----- ----------------------------------  2/14 [tld]
    Uninstalling regex-2023.10.3:
   ----- ----------------------------------  2/14 [tld]
   -------- -------------------------------  3/14 [regex]
      Successfully uninstalled regex-2023.10.3
   -------- -------------------------------  3/14 [regex]
   -------- -------------------------------  3/14 [regex]
  Attempting uninstall: python-dateutil
   -------- -------------------------------  3/14 [regex]
   ----------- ----------------------------  4/14 [python-dateutil]
    Found existing installation: python-dateutil 2.8.2
   ----------- ----------------------------  4/14 [python-dateutil]
    Uninstalling python-dateutil-2.8.2:
   ----------- ----------------------------  4/14 [python-dateutil]
      Successfully uninstalled python-dateutil-2.8.2
   ----------- ----------------------------  4/14 [python-dateutil]
   ----------- ----------------------------  4/14 [python-dateutil]
   ----------- ----------------------------  4/14 [python-dateutil]
  Attempting uninstall: lxml
   ----------- ----------------------------  4/14 [python-dateutil]
    Found existing installation: lxml 5.2.1
   ----------- ----------------------------  4/14 [python-dateutil]
   -------------- -------------------------  5/14 [lxml]
    Uninstalling lxml-5.2.1:
   -------------- -------------------------  5/14 [lxml]
      Successfully uninstalled lxml-5.2.1
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
   -------------- -------------------------  5/14 [lxml]
  Attempting uninstall: charset_normalizer
   -------------- -------------------------  5/14 [lxml]
    Found existing installation: charset-normalizer 3.3.0
   -------------- -------------------------  5/14 [lxml]
    Uninstalling charset-normalizer-3.3.0:
   -------------- -------------------------  5/14 [lxml]
   ----------------- ----------------------  6/14 [charset_normalizer]
      Successfully uninstalled charset-normalizer-3.3.0
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
   ----------------- ----------------------  6/14 [charset_normalizer]
  Attempting uninstall: babel
   ----------------- ----------------------  6/14 [charset_normalizer]
    Found existing installation: Babel 2.14.0
   ----------------- ----------------------  6/14 [charset_normalizer]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
    Uninstalling Babel-2.14.0:
   -------------------- -------------------  7/14 [babel]
      Successfully uninstalled Babel-2.14.0
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   -------------------- -------------------  7/14 [babel]
   ---------------------- -----------------  8/14 [lxml_html_clean]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ------------------------- --------------  9/14 [dateparser]
   ---------------------------- ----------- 10/14 [courlan]
   ------------------------------- -------- 11/14 [htmldate]
   ---------------------------------- ----- 12/14 [justext]
   ---------------------------------- ----- 12/14 [justext]
   ------------------------------------- -- 13/14 [trafilatura]
   ------------------------------------- -- 13/14 [trafilatura]
   ---------------------------------------- 14/14 [trafilatura]

Successfully installed babel-2.18.0 charset_normalizer-3.4.9 courlan-1.4.0 dateparser-1.4.1 htmldate-1.10.0 justext-3.0.2 lxml-6.1.1 lxml_html_clean-0.4.5 python-dateutil-2.9.0.post0 pytz-2026.2 regex-2026.7.10 tld-0.13.2 trafilatura-2.1.0 tzlocal-5.4.4

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\~xml'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\~harset_normalizer'.
  You can safely remove it manually.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Import Trafilatura**

In [ ]:
# ============================================================
# CELL 14: IMPORT TRAFILATURA
# ============================================================

import trafilatura

**ARTICLE EXTRACTION FUNCTION**

In [ ]:
# ============================================================
# CELL 15: ARTICLE EXTRACTION FUNCTION
# ============================================================

def extract_article(url):
    """
    Download a webpage and extract the main article using Trafilatura.
    Returns:
        Clean article text or None.
    """

    try:

        downloaded = trafilatura.fetch_url(url)

        if downloaded is None:
            return None

        text = trafilatura.extract(
            downloaded,
            include_comments=False,
            include_tables=False,
            include_images=False,
            favor_precision=True
        )

        return text

    except Exception as e:

        print(url)
        print(e)

        return None

**EXTRACT CLEAN ARTICLE TEXT**

In [ ]:
# ============================================================
# CELL 16: EXTRACT CLEAN ARTICLE TEXT
# ============================================================

clean_articles = []

for i, row in tqdm(df.iterrows(), total=len(df)):

    article = extract_article(row["url"])

    if article is None:
        continue

    if len(article) < 150:
        continue

    clean_articles.append({

        "url": row["url"],

        "title": row["title"],

        "description": row["description"],

        "text": article

    })

clean_df = pd.DataFrame(clean_articles)

print()

print("Clean Articles:", len(clean_df))

clean_df.head()

  0%|          | 0/107 [00:00<?, ?it/s]

100%|██████████| 107/107 [07:01<00:00,  3.94s/it]

Clean Articles: 79

,url,title,description,text
0,http://publicservice.go.ke/about-us/,About Us - Public Service Commission,,About Us\n1954\nYear Established\n20K +\nYouth...
1,http://publicservice.go.ke/news-updates/,News Updates - Public Service Commission,,The Public Service Commission (PSC) will roll ...
2,http://publicservice.go.ke/programmes/,Programmes - Public Service Commission,,Programmes\nPromote Inclusivity\nPromote Entre...
3,https://accounts.ecitizen.go.ke/en,Home · Government of Kenya services simplified,"Government of Kenya online portal offers 16,00...",Government of Kenya services\n simp...
4,https://dis.ecitizen.go.ke/,Welcome,Directorate of Immigration,The Directorate of Immigration Services is a D...

**SAVE CLEAN DATASET**

In [ ]:
# ============================================================
# CELL 17: SAVE CLEAN DATASET
# ============================================================

clean_df.to_excel(
    "01_Clean_Governance_Articles.xlsx",
    index=False
)

print("Backup saved successfully.")

Backup saved successfully.

**DEFINING PSA VOCABULARY**

In [ ]:
# ============================================================
# CELL 18: PSA VOCABULARY
# ============================================================

ACTION_WORDS = [

    "register",
    "verify",
    "report",
    "apply",
    "submit",
    "renew",
    "collect",
    "attend",
    "participate",
    "visit",
    "download",
    "call",
    "pay",
    "complete",
    "obtain",
    "check",
    "update",
    "book",
    "access"

]

URGENCY_WORDS = [

    "deadline",
    "urgent",
    "immediately",
    "before",
    "last day",
    "expires",
    "warning",
    "alert",
    "important",
    "reminder",
    "must",
    "required",
    "mandatory"

]

AUDIENCE_WORDS = [

    "citizens",
    "residents",
    "public",
    "voters",
    "applicants",
    "farmers",
    "students",
    "businesses",
    "employers",
    "taxpayers",
    "drivers",
    "parents",
    "workers"

]

GOVERNMENT_AGENCIES = [

    "IEBC",
    "EACC",
    "NTSA",
    "KRA",
    "NEMA",
    "SHA",
    "Ministry",
    "Government",
    "County",
    "eCitizen",
    "Parliament",
    "Senate",
    "Commission"

]

**PSA SCORING ENGINE**

In [ ]:
# ============================================================
# CELL 19: PSA SCORING ENGINE
# ============================================================

def psa_score(text):

    if text is None:
        return 0

    text = text.lower()

    score = 0

    # -----------------------
    # Action words
    # -----------------------

    score += sum(word in text for word in ACTION_WORDS)

    # -----------------------
    # Urgency
    # -----------------------

    score += 2 * sum(word in text for word in URGENCY_WORDS)

    # -----------------------
    # Target audience
    # -----------------------

    score += sum(word in text for word in AUDIENCE_WORDS)

    # -----------------------
    # Government agencies
    # -----------------------

    score += sum(word.lower() in text for word in GOVERNMENT_AGENCIES)

    return score

**COMPUTE PSA SCORE**

In [ ]:
# ============================================================
# CELL 20: COMPUTE PSA SCORE
# ============================================================

clean_df["PSA_Score"] = clean_df["text"].apply(psa_score)

clean_df.head()

,url,title,description,text,PSA_Score
0,http://publicservice.go.ke/about-us/,About Us - Public Service Commission,,About Us\n1954\nYear Established\n20K +\nYouth...,4
1,http://publicservice.go.ke/news-updates/,News Updates - Public Service Commission,,The Public Service Commission (PSC) will roll ...,4
2,http://publicservice.go.ke/programmes/,Programmes - Public Service Commission,,Programmes\nPromote Inclusivity\nPromote Entre...,4
3,https://accounts.ecitizen.go.ke/en,Home · Government of Kenya services simplified,"Government of Kenya online portal offers 16,00...",Government of Kenya services\n simp...,8
4,https://dis.ecitizen.go.ke/,Welcome,Directorate of Immigration,The Directorate of Immigration Services is a D...,5

**FILTER PSA ARTICLES**

In [ ]:
# ============================================================
# CELL 21: FILTER PSA ARTICLES
# ============================================================

PSA_THRESHOLD = 5

psa_df = clean_df[
    clean_df["PSA_Score"] >= PSA_THRESHOLD
].copy()

print(f"PSAs Detected: {len(psa_df)}")

psa_df.head()

PSAs Detected: 41

,url,title,description,text,PSA_Score
3,https://accounts.ecitizen.go.ke/en,Home · Government of Kenya services simplified,"Government of Kenya online portal offers 16,00...",Government of Kenya services\n simp...,8
4,https://dis.ecitizen.go.ke/,Welcome,Directorate of Immigration,The Directorate of Immigration Services is a D...,5
5,https://eacc.go.ke/en/default/feed/eacc-and-bu...,EACC urges counties to refrain from graft for ...,,EACC urges counties to refrain from graft for ...,15
6,https://eacc.go.ke/en/default/feed/two-public-...,Two public officers arrested for diversion of ...,,Two public officers arrested for diversion of ...,9
7,https://eacc.go.ke/en/default/news-updates/,News & Updates - EACC,,Ethics and Anti-Corruption Commission gathers ...,5

**SAVE PSA DATASET TO CSV**

In [ ]:
# ============================================================
# CELL 22: SAVE PSA DATASET TO CSV
# ============================================================

import os

# Create output folder if it doesn't exist
os.makedirs("output", exist_ok=True)

# Save the detected PSAs
csv_file = "output/Governance_PSA_Dataset.csv"

psa_df.to_csv(
    csv_file,
    index=False,
    encoding="utf-8-sig"   # Ensures Excel opens it correctly
)

print("="*60)
print("Dataset successfully saved!")
print(f"Location: {csv_file}")
print(f"Total PSA Records: {len(psa_df)}")
print("="*60)

PermissionError: [Errno 13] Permission denied: 'output/Governance_PSA_Dataset.csv'

**VERIFY**

In [ ]:
# ============================================================
# CELL 23: READ THE CSV BACK
# ============================================================

saved_df = pd.read_csv("output/Governance_PSA_Dataset.csv")

print(saved_df.shape)

saved_df.head()

(41, 5)

,url,title,description,text,PSA_Score
0,https://accounts.ecitizen.go.ke/en,Home · Government of Kenya services simplified,"Government of Kenya online portal offers 16,00...",Government of Kenya services\n simp...,8
1,https://dis.ecitizen.go.ke/,Welcome,Directorate of Immigration,The Directorate of Immigration Services is a D...,5
2,https://eacc.go.ke/en/default/feed/eacc-and-bu...,EACC urges counties to refrain from graft for ...,NaN,EACC urges counties to refrain from graft for ...,15
3,https://eacc.go.ke/en/default/feed/two-public-...,Two public officers arrested for diversion of ...,NaN,Two public officers arrested for diversion of ...,9
4,https://eacc.go.ke/en/default/news-updates/,News & Updates - EACC,NaN,Ethics and Anti-Corruption Commission gathers ...,5

# **Transformer**

In [ ]:
# ============================================================
# CELL 24
# ============================================================

!pip install -U transformers torch accelerate sentencepiece

In [ ]:
# ============================================================
# CELL 25
# ============================================================

import os

os.environ["USE_TF"] = "0"
os.environ["TRANSFORMERS_NO_TF"] = "1"

print("TensorFlow disabled.")

TensorFlow disabled.

In [ ]:
%pip uninstall torch torchvision torchaudio -y

Found existing installation: torch 2.7.1+cu118
Uninstalling torch-2.7.1+cu118:
  Successfully uninstalled torch-2.7.1+cu118
Found existing installation: torchaudio 2.7.1+cu118
Uninstalling torchaudio-2.7.1+cu118:
  Successfully uninstalled torchaudio-2.7.1+cu118
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\~orch'.
You can safely remove it manually.
WARNING: Skipping torchvision as it is not installed.

In [ ]:
%pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading torch-2.13.0%2Bcpu-cp311-cp311-win_amd64.whl.metadata (39 kB)
Collecting torchvision
  Downloading torchvision-0.28.0%2Bcpu-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Collecting torchaudio
  Downloading torchaudio-2.11.0%2Bcpu-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: filelock in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (3.16.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: setuptools>=77.0.3 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec>=0.8.5 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torch) (2024.10.0)
Requirement already satisfied: numpy in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from torchvision) (10.0.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jinja2->torch) (2.1.3)
Downloading torch-2.13.0%2Bcpu-cp311-cp311-win_amd64.whl (121.9 MB)
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/121.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/121.9 MB ? eta -:--:--
   ---------------------------------------- 1.0/121.9 MB 2.8 MB/s eta 0:00:44
    --------------------------------------- 2.4/121.9 MB 4.3 MB/s eta 0:00:28
   -- ------------------------------------- 6.3/121.9 MB 8.6 MB/s eta 0:00:14
   ----- ---------------------------------- 16.8/121.9 MB 17.9 MB/s eta 0:00:06
   -------- ------------------------------- 26.7/121.9 MB 23.5 MB/s eta 0:00:05
   --------- ------------------------------ 28.0/121.9 MB 24.4 MB/s eta 0:00:04
   --------- ------------------------------ 28.3/121.9 MB 20.4 MB/s eta 0:00:05
   --------- ------------------------------ 29.6/121.9 MB 18.6 MB/s eta 0:00:05
   ------------ --------------------------- 37.2/121.9 MB 18.8 MB/s eta 0:00:05
   ------------- -------------------------- 42.2/121.9 MB 20.0 MB/s eta 0:00:04
   -------------- ------------------------- 43.0/121.9 MB 18.1 MB/s eta 0:00:05
   -------------- ------------------------- 43.3/121.9 MB 17.1 MB/s eta 0:00:05
   -------------- ------------------------- 44.3/121.9 MB 16.5 MB/s eta 0:00:05
   --------------- ------------------------ 48.2/121.9 MB 16.0 MB/s eta 0:00:05
   ---------------- ----------------------- 49.0/121.9 MB 15.1 MB/s eta 0:00:05
   ---------------- ----------------------- 50.1/121.9 MB 14.7 MB/s eta 0:00:05
   ---------------- ----------------------- 51.6/121.9 MB 14.5 MB/s eta 0:00:05
   ----------------- ---------------------- 54.5/121.9 MB 14.6 MB/s eta 0:00:05
   ------------------- -------------------- 59.0/121.9 MB 14.9 MB/s eta 0:00:05
   ------------------- -------------------- 59.8/121.9 MB 14.5 MB/s eta 0:00:05
   -------------------- ------------------- 62.7/121.9 MB 13.9 MB/s eta 0:00:05
   ---------------------- ----------------- 69.7/121.9 MB 15.2 MB/s eta 0:00:04
   ----------------------- ---------------- 72.9/121.9 MB 15.0 MB/s eta 0:00:04
   ------------------------ --------------- 73.4/121.9 MB 14.6 MB/s eta 0:00:04
   ------------------------- -------------- 78.9/121.9 MB 14.7 MB/s eta 0:00:03
   -------------------------- ------------- 81.8/121.9 MB 14.7 MB/s eta 0:00:03
   ---------------------------- ----------- 85.7/121.9 MB 14.9 MB/s eta 0:00:03
   ----------------------------- ---------- 90.2/121.9 MB 15.0 MB/s eta 0:00:03
   ------------------------------ --------- 91.8/121.9 MB 15.2 MB/s eta 0:00:02
   ------------------------------- -------- 95.9/121.9 MB 15.2 MB/s eta 0:00:02
   -------------------------------- ------- 99.4/121.9 MB 15.1 MB/s eta 0:00:02
   ---------------------------------- ---- 106.7/121.9 MB 15.6 MB/s eta 0:00:01
   ---------------------------------- ---- 107.0/121.9 MB 15.3 MB/s eta 0:00:01
   ------------------------------------ -- 115.3/121.9 MB 15.9 MB/s eta 0:00:01
   ------------------------------------- - 115.9/121.9 MB 15.7 MB/s eta 0:00:01
   --------------------------------------  121.6/121.9 MB 15.8 MB/s eta 0:00:01
   --------------------------------------  121.6/121.9 MB 15.8 MB/s eta 0:00:01
   --------------------------------------  121.6/121.9 MB 15.8 MB/s eta 0:00:01
   --------------------------------------  121.6/121.9 MB 15.8 MB/s eta 0:00:01
   --------------------------------------  121.6/121.9 MB 15.8 MB/s eta 0:00:01
   ---------------------------------------- 121.9/121.9 MB 14.2 MB/s  0:00:08
Downloading torchvision-0.28.0%2Bcpu-cp311-cp311-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   --------------------------- ------------ 2.6/3.8 MB 37.4 MB/s eta 0:00:01
   -------------------------------------- - 3.7/3.8 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 7.8 MB/s  0:00:00
Downloading torchaudio-2.11.0%2Bcpu-cp311-cp311-win_amd64.whl (326 kB)
Installing collected packages: torchaudio, torch, torchvision

   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import sys

print(sys.version)
print(sys.executable)

3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
c:\Users\Admin\AppData\Local\Programs\Python\Python311\python.exe

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [ ]:
# ============================================================
# CELL 26
# ============================================================

import torch

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification

print(torch.__version__)

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "c:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [ ]:
# ============================================================
# CELL 25: IMPORT NLP LIBRARIES
# ============================================================

from transformers import pipeline

print("Transformers imported successfully.")

C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Transformers imported successfully.

In [ ]:
# ============================================================
# CELL 27
# ============================================================

MODEL_NAME = "MoritzLaurer/deberta-v3-base-zeroshot-v1"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

device = "cuda" if torch.cuda.is_available() else "cpu"

model.to(device)

print("Running on:", device)

In [ ]:
# ============================================================
# CELL 26: LOAD THE MODEL
# ============================================================

classifier = pipeline(
    task="zero-shot-classification",
    model="facebook/bart-large-mnli"
)

print("Model loaded successfully.")

:

In [ ]:
# ============================================================
# CELL 27: GOVERNANCE LABELS
# ============================================================

labels = [

    "Anti-Corruption",

    "Public Participation",

    "Elections and Voter Education",

    "Public Service Delivery",

    "Devolution and Local Governance"

]

print(labels)

In [ ]:
# ============================================================
# CELL 28: TEST THE MODEL
# ============================================================

sample = """

The Independent Electoral and Boundaries Commission
reminds all registered voters to verify their voter
registration details before the registration deadline.

"""

result = classifier(
    sample,
    labels
)

print(result)

In [ ]:
# ============================================================
# CELL 29: CLASSIFY A GOVERNANCE PSA
# ============================================================

def classify_psa(text):

    if not isinstance(text, str):
        return "Unknown", 0.0

    try:

        prediction = classifier(
            text[:1000],   # Limit input length
            labels
        )

        return (

            prediction["labels"][0],

            prediction["scores"][0]

        )

    except Exception:

        return "Unknown", 0.0

In [ ]:
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tqdm in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (4.68.4)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tqdm) (0.4.6)

In [ ]:
# ============================================================
# CELL 30: CLASSIFY ALL PSAs
# ============================================================
from tqdm import tqdm
predictions = []

confidences = []

for article in tqdm(psa_df["text"]):

    category, confidence = classify_psa(article)

    predictions.append(category)

    confidences.append(confidence)

psa_df["Category"] = predictions

psa_df["Confidence"] = confidences

psa_df.head()

NameError: name 'psa_df' is not defined